apiVersion: v1
kind: Pod
metadata:
  name: hello-kube-pod # name duoc show tren console
  labels:
    app: web # duoc dung de cac object khac tuong tac
spec:
  containers:
    - name: hello-kube
      image: fhsinchy/hello-kube
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80 # expose port 
  restartPolicy: Always
